---
# Copyright (c) 2021 Cisco and/or its affiliates.
# 
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
# 
#                https://developer.cisco.com/docs/licenses
# 
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
# 
# AUTHOR(s): Francisco Quiroz <frquiroz@cisco.com>
- name: Deleting Tenant with CSV file
  hosts: "{{ apic }}"
  connection: local
  gather_facts: false
  no_log: true

  tasks:
  - name: Read data from CSV file to be used to configure ACI
    read_csv:
      path: tenant.csv
      # key: tenant
    register: mytenant
    delegate_to: localhost

  - name: Delete Tenants using CSV and loop
    aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ new_user }}"
      password: "{{ password }}"
      #private_key: "{{ new_user }}.key"
      tenant: "{{ item.tenant }}"
      description: "Tenant configured by Ansible"
      validate_certs: false
      state: absent
    loop: "{{ mytenant.list }}"
