---
# Copyright (c) 2021 Cisco and/or its affiliates.
# 
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
# 
#                https://developer.cisco.com/docs/licenses
# 
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
# 
# AUTHOR(s): Francisco Quiroz <frquiroz@cisco.com>
- name: Automation XR - ICE
  hosts: "{{ terraform_server }}"
  connection: local
  gather_facts: no
  
  tasks:
  - name: Basic deploy of a service
    community.general.terraform:
      project_path: "{{ project_path }}"
      #binary_path: "{{ terraform_path }}"
      state: present
      force_init: true
    register: plan
  
  - debug:
      msg: '{{plan.stdout_lines}}'
  
